//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 14. 6. 2013 16:24:56
namespace SkautSIS.PersonGroups.PersonGroupsModel
{
    
    /// <summary>
    /// There are no comments for PersonGroupsContext in the schema.
    /// </summary>
    public partial class PersonGroupsContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new PersonGroupsContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PersonGroupsContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("SkautSIS.Services.PersonGroups.Models", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("SkautSIS.PersonGroups.PersonGroupsModel", typeName.Substring(37)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("SkautSIS.PersonGroups.PersonGroupsModel", global::System.StringComparison.Ordinal))
            {
                return string.Concat("SkautSIS.Services.PersonGroups.Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Persons in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Person> Persons
        {
            get
            {
                if ((this._Persons == null))
                {
                    this._Persons = base.CreateQuery<Person>("Persons");
                }
                return this._Persons;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Person> _Persons;
        /// <summary>
        /// There are no comments for PersonGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PersonGroup> PersonGroups
        {
            get
            {
                if ((this._PersonGroups == null))
                {
                    this._PersonGroups = base.CreateQuery<PersonGroup>("PersonGroups");
                }
                return this._PersonGroups;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PersonGroup> _PersonGroups;
        /// <summary>
        /// There are no comments for EdmMetadatas in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<EdmMetadata> EdmMetadatas
        {
            get
            {
                if ((this._EdmMetadatas == null))
                {
                    this._EdmMetadatas = base.CreateQuery<EdmMetadata>("EdmMetadatas");
                }
                return this._EdmMetadatas;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<EdmMetadata> _EdmMetadatas;
        /// <summary>
        /// There are no comments for Persons in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPersons(Person person)
        {
            base.AddObject("Persons", person);
        }
        /// <summary>
        /// There are no comments for PersonGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPersonGroups(PersonGroup personGroup)
        {
            base.AddObject("PersonGroups", personGroup);
        }
        /// <summary>
        /// There are no comments for EdmMetadatas in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToEdmMetadatas(EdmMetadata edmMetadata)
        {
            base.AddObject("EdmMetadatas", edmMetadata);
        }
    }
    /// <summary>
    /// There are no comments for SkautSIS.Services.PersonGroups.Models.Person in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PersonId
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("PersonId")]
    public partial class Person
    {
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="personId">Initial value of PersonId.</param>
        /// <param name="skautIsUserId">Initial value of SkautIsUserId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Person CreatePerson(int personId, int skautIsUserId)
        {
            Person person = new Person();
            person.PersonId = personId;
            person.SkautIsUserId = skautIsUserId;
            return person;
        }
        /// <summary>
        /// There are no comments for Property PersonId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PersonId
        {
            get
            {
                return this._PersonId;
            }
            set
            {
                this.OnPersonIdChanging(value);
                this._PersonId = value;
                this.OnPersonIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PersonId;
        partial void OnPersonIdChanging(int value);
        partial void OnPersonIdChanged();
        /// <summary>
        /// There are no comments for Property SkautIsUserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SkautIsUserId
        {
            get
            {
                return this._SkautIsUserId;
            }
            set
            {
                this.OnSkautIsUserIdChanging(value);
                this._SkautIsUserId = value;
                this.OnSkautIsUserIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SkautIsUserId;
        partial void OnSkautIsUserIdChanging(int value);
        partial void OnSkautIsUserIdChanged();
        /// <summary>
        /// There are no comments for Groups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<PersonGroup> Groups
        {
            get
            {
                return this._Groups;
            }
            set
            {
                if ((value != null))
                {
                    this._Groups = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<PersonGroup> _Groups = new global::System.Collections.ObjectModel.Collection<PersonGroup>();
    }
    /// <summary>
    /// There are no comments for SkautSIS.Services.PersonGroups.Models.PersonGroup in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PersonGroupId
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("PersonGroupId")]
    public partial class PersonGroup
    {
        /// <summary>
        /// Create a new PersonGroup object.
        /// </summary>
        /// <param name="personGroupId">Initial value of PersonGroupId.</param>
        /// <param name="displayName">Initial value of DisplayName.</param>
        /// <param name="type">Initial value of Type.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PersonGroup CreatePersonGroup(int personGroupId, string displayName, int type)
        {
            PersonGroup personGroup = new PersonGroup();
            personGroup.PersonGroupId = personGroupId;
            personGroup.DisplayName = displayName;
            personGroup.Type = type;
            return personGroup;
        }
        /// <summary>
        /// There are no comments for Property PersonGroupId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PersonGroupId
        {
            get
            {
                return this._PersonGroupId;
            }
            set
            {
                this.OnPersonGroupIdChanging(value);
                this._PersonGroupId = value;
                this.OnPersonGroupIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PersonGroupId;
        partial void OnPersonGroupIdChanging(int value);
        partial void OnPersonGroupIdChanged();
        /// <summary>
        /// There are no comments for Property DisplayName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DisplayName
        {
            get
            {
                return this._DisplayName;
            }
            set
            {
                this.OnDisplayNameChanging(value);
                this._DisplayName = value;
                this.OnDisplayNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DisplayName;
        partial void OnDisplayNameChanging(string value);
        partial void OnDisplayNameChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Type;
        partial void OnTypeChanging(int value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Persons in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Person> Persons
        {
            get
            {
                return this._Persons;
            }
            set
            {
                if ((value != null))
                {
                    this._Persons = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Person> _Persons = new global::System.Collections.ObjectModel.Collection<Person>();
    }
    /// <summary>
    /// There are no comments for SkautSIS.Services.PersonGroups.Models.EdmMetadata in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class EdmMetadata
    {
        /// <summary>
        /// Create a new EdmMetadata object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static EdmMetadata CreateEdmMetadata(int ID)
        {
            EdmMetadata edmMetadata = new EdmMetadata();
            edmMetadata.Id = ID;
            return edmMetadata;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ModelHash in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModelHash
        {
            get
            {
                return this._ModelHash;
            }
            set
            {
                this.OnModelHashChanging(value);
                this._ModelHash = value;
                this.OnModelHashChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModelHash;
        partial void OnModelHashChanging(string value);
        partial void OnModelHashChanged();
    }
}
