//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 14. 6. 2013 17:00:38
namespace SkautSIS.Users.UsersModel
{
    
    /// <summary>
    /// There are no comments for UsersContext in the schema.
    /// </summary>
    public partial class UsersContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new UsersContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public UsersContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("SkautSIS.Services.Users.Models", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("SkautSIS.Users.UsersModel", typeName.Substring(30)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("SkautSIS.Users.UsersModel", global::System.StringComparison.Ordinal))
            {
                return string.Concat("SkautSIS.Services.Users.Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<User> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<User>("Users");
                }
                return this._Users;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<User> _Users;
        /// <summary>
        /// There are no comments for UsersRelationship in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<UsersRelationship> UsersRelationship
        {
            get
            {
                if ((this._UsersRelationship == null))
                {
                    this._UsersRelationship = base.CreateQuery<UsersRelationship>("UsersRelationship");
                }
                return this._UsersRelationship;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<UsersRelationship> _UsersRelationship;
        /// <summary>
        /// There are no comments for UsersRelationshipRequest in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<UsersRelationshipRequest> UsersRelationshipRequest
        {
            get
            {
                if ((this._UsersRelationshipRequest == null))
                {
                    this._UsersRelationshipRequest = base.CreateQuery<UsersRelationshipRequest>("UsersRelationshipRequest");
                }
                return this._UsersRelationshipRequest;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<UsersRelationshipRequest> _UsersRelationshipRequest;
        /// <summary>
        /// There are no comments for EdmMetadatas in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<EdmMetadata> EdmMetadatas
        {
            get
            {
                if ((this._EdmMetadatas == null))
                {
                    this._EdmMetadatas = base.CreateQuery<EdmMetadata>("EdmMetadatas");
                }
                return this._EdmMetadatas;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<EdmMetadata> _EdmMetadatas;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
        /// <summary>
        /// There are no comments for UsersRelationship in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUsersRelationship(UsersRelationship usersRelationship)
        {
            base.AddObject("UsersRelationship", usersRelationship);
        }
        /// <summary>
        /// There are no comments for UsersRelationshipRequest in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUsersRelationshipRequest(UsersRelationshipRequest usersRelationshipRequest)
        {
            base.AddObject("UsersRelationshipRequest", usersRelationshipRequest);
        }
        /// <summary>
        /// There are no comments for EdmMetadatas in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToEdmMetadatas(EdmMetadata edmMetadata)
        {
            base.AddObject("EdmMetadatas", edmMetadata);
        }
    }
    /// <summary>
    /// There are no comments for SkautSIS.Services.Users.Models.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class User
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="skautIsPersonId">Initial value of SkautIsPersonId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static User CreateUser(int ID, int skautIsPersonId)
        {
            User user = new User();
            user.Id = ID;
            user.SkautIsPersonId = skautIsPersonId;
            return user;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property SkautIsPersonId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SkautIsPersonId
        {
            get
            {
                return this._SkautIsPersonId;
            }
            set
            {
                this.OnSkautIsPersonIdChanging(value);
                this._SkautIsPersonId = value;
                this.OnSkautIsPersonIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SkautIsPersonId;
        partial void OnSkautIsPersonIdChanging(int value);
        partial void OnSkautIsPersonIdChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property NickName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NickName
        {
            get
            {
                return this._NickName;
            }
            set
            {
                this.OnNickNameChanging(value);
                this._NickName = value;
                this.OnNickNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NickName;
        partial void OnNickNameChanging(string value);
        partial void OnNickNameChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
    }
    /// <summary>
    /// There are no comments for SkautSIS.Services.Users.Models.UsersRelationship in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class UsersRelationship
    {
        /// <summary>
        /// Create a new UsersRelationship object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static UsersRelationship CreateUsersRelationship(int ID)
        {
            UsersRelationship usersRelationship = new UsersRelationship();
            usersRelationship.Id = ID;
            return usersRelationship;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Parent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public User Parent
        {
            get
            {
                return this._Parent;
            }
            set
            {
                this._Parent = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private User _Parent;
        /// <summary>
        /// There are no comments for Child in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public User Child
        {
            get
            {
                return this._Child;
            }
            set
            {
                this._Child = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private User _Child;
    }
    /// <summary>
    /// There are no comments for ComplexType SkautSIS.Services.Users.Models.StateWrapper in the schema.
    /// </summary>
    public partial class StateWrapper
    {
        /// <summary>
        /// Create a new StateWrapper object.
        /// </summary>
        /// <param name="value">Initial value of Value.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static StateWrapper CreateStateWrapper(int value)
        {
            StateWrapper stateWrapper = new StateWrapper();
            stateWrapper.Value = value;
            return stateWrapper;
        }
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Value;
        partial void OnValueChanging(int value);
        partial void OnValueChanged();
    }
    /// <summary>
    /// There are no comments for SkautSIS.Services.Users.Models.UsersRelationshipRequest in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class UsersRelationshipRequest
    {
        /// <summary>
        /// Create a new UsersRelationshipRequest object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="childBirthdate">Initial value of ChildBirthdate.</param>
        /// <param name="state">Initial value of State.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static UsersRelationshipRequest CreateUsersRelationshipRequest(int ID, global::System.DateTime childBirthdate, StateWrapper state)
        {
            UsersRelationshipRequest usersRelationshipRequest = new UsersRelationshipRequest();
            usersRelationshipRequest.Id = ID;
            usersRelationshipRequest.ChildBirthdate = childBirthdate;
            if ((state == null))
            {
                throw new global::System.ArgumentNullException("state");
            }
            usersRelationshipRequest.State = state;
            return usersRelationshipRequest;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ChildFirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ChildFirstName
        {
            get
            {
                return this._ChildFirstName;
            }
            set
            {
                this.OnChildFirstNameChanging(value);
                this._ChildFirstName = value;
                this.OnChildFirstNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ChildFirstName;
        partial void OnChildFirstNameChanging(string value);
        partial void OnChildFirstNameChanged();
        /// <summary>
        /// There are no comments for Property ChildLastNmae in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ChildLastNmae
        {
            get
            {
                return this._ChildLastNmae;
            }
            set
            {
                this.OnChildLastNmaeChanging(value);
                this._ChildLastNmae = value;
                this.OnChildLastNmaeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ChildLastNmae;
        partial void OnChildLastNmaeChanging(string value);
        partial void OnChildLastNmaeChanged();
        /// <summary>
        /// There are no comments for Property ChildBirthdate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ChildBirthdate
        {
            get
            {
                return this._ChildBirthdate;
            }
            set
            {
                this.OnChildBirthdateChanging(value);
                this._ChildBirthdate = value;
                this.OnChildBirthdateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ChildBirthdate;
        partial void OnChildBirthdateChanging(global::System.DateTime value);
        partial void OnChildBirthdateChanged();
        /// <summary>
        /// There are no comments for Property State in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public StateWrapper State
        {
            get
            {
                if (((this._State == null) 
                            && (this._StateInitialized != true)))
                {
                    this._State = new StateWrapper();
                    this._StateInitialized = true;
                }
                return this._State;
            }
            set
            {
                this.OnStateChanging(value);
                this._State = value;
                this._StateInitialized = true;
                this.OnStateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private StateWrapper _State;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _StateInitialized;
        partial void OnStateChanging(StateWrapper value);
        partial void OnStateChanged();
        /// <summary>
        /// There are no comments for Parent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public User Parent
        {
            get
            {
                return this._Parent;
            }
            set
            {
                this._Parent = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private User _Parent;
    }
    /// <summary>
    /// There are no comments for SkautSIS.Services.Users.Models.EdmMetadata in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class EdmMetadata
    {
        /// <summary>
        /// Create a new EdmMetadata object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static EdmMetadata CreateEdmMetadata(int ID)
        {
            EdmMetadata edmMetadata = new EdmMetadata();
            edmMetadata.Id = ID;
            return edmMetadata;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ModelHash in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModelHash
        {
            get
            {
                return this._ModelHash;
            }
            set
            {
                this.OnModelHashChanging(value);
                this._ModelHash = value;
                this.OnModelHashChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModelHash;
        partial void OnModelHashChanging(string value);
        partial void OnModelHashChanged();
    }
}
